root: true
env:
  browser: false
  es2021: true
extends:
    - 'eslint:recommended'
    - 'plugin:import/typescript'
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  # sourceType: module
plugins:
  - '@typescript-eslint'

rules:
  curly: 2
  no-prototype-builtins: 0
